theme: minima
layout: default
title: Code Samples for SmartSVG Integration
description: Learn how to use SmartSVG in all your projects.
kramdown:
  input: GFM
plugins:
  - jemoji
minima:
  skin: dark
